/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dnsoft.dentista.views;

import com.dnsoft.dentista.utiles.InternalFrameEstandar;

/**
 *
 * @author Diego
 */
public class PacientesView extends InternalFrameEstandar {

    /**
     * Creates new form NewJInternalFrame
     */
    public PacientesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuEntradas = new javax.swing.JPopupMenu();
        btnEnviarSMS = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnCuentas = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        btnTratamientos = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        btnOdontograma = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        btnImagenes = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        btnAnamnesis = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        btnHistoriaConsultas = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        btnProximaConsulta = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        btnTrabajosLaboratorio = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        btnModificarDatos = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new botones.BotonNuevo();
        btnVolver = new botones.BotonVolver();
        btnModificar = new botones.BotonEdicion();
        btnAcciones = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        btnEnviarSMS.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnEnviarSMS.setText("Enviar SMS");
        btnEnviarSMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarSMSActionPerformed(evt);
            }
        });
        menuEntradas.add(btnEnviarSMS);
        menuEntradas.add(jSeparator1);

        btnCuentas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCuentas.setText("Cuenta");
        btnCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentasActionPerformed(evt);
            }
        });
        menuEntradas.add(btnCuentas);
        menuEntradas.add(jSeparator12);

        btnTratamientos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnTratamientos.setText("Tratamientos y planes");
        btnTratamientos.setActionCommand("Tratamientos");
        btnTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTratamientosActionPerformed(evt);
            }
        });
        menuEntradas.add(btnTratamientos);
        menuEntradas.add(jSeparator13);

        btnOdontograma.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnOdontograma.setText("Odontograma");
        btnOdontograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdontogramaActionPerformed(evt);
            }
        });
        menuEntradas.add(btnOdontograma);
        menuEntradas.add(jSeparator14);

        btnImagenes.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnImagenes.setText("Imagenes");
        menuEntradas.add(btnImagenes);
        menuEntradas.add(jSeparator15);

        btnAnamnesis.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnAnamnesis.setText("Anamnesis");
        menuEntradas.add(btnAnamnesis);
        menuEntradas.add(jSeparator16);

        btnHistoriaConsultas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnHistoriaConsultas.setText("Historia de Consultas");
        btnHistoriaConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaConsultasActionPerformed(evt);
            }
        });
        menuEntradas.add(btnHistoriaConsultas);
        menuEntradas.add(jSeparator17);

        btnProximaConsulta.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnProximaConsulta.setText("Próxima consulta");
        btnProximaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximaConsultaActionPerformed(evt);
            }
        });
        menuEntradas.add(btnProximaConsulta);
        menuEntradas.add(jSeparator18);

        btnTrabajosLaboratorio.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnTrabajosLaboratorio.setText("Trabajos de laboratorio");
        btnTrabajosLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajosLaboratorioActionPerformed(evt);
            }
        });
        menuEntradas.add(btnTrabajosLaboratorio);
        menuEntradas.add(jSeparator19);

        btnModificarDatos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnModificarDatos.setText("Modificar Datos");
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });
        menuEntradas.add(btnModificarDatos);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnNuevo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnVolver, gridBagConstraints);

        btnModificar.setEnabled(false);
        btnModificar.setText("Editar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnModificar, gridBagConstraints);

        btnAcciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnAcciones.setText("Funciones ");
        btnAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAcciones, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        jLabel3.setText("Pacientes");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(jLabel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(txtBusqueda, gridBagConstraints);

        jLabel1.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel5.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel5, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionesActionPerformed

        menuEntradas.show(btnAcciones, btnAcciones.getWidth() / 2, btnAcciones.getHeight() / 2);
    }//GEN-LAST:event_btnAccionesActionPerformed

    private void btnEnviarSMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarSMSActionPerformed

    }//GEN-LAST:event_btnEnviarSMSActionPerformed

    private void btnCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentasActionPerformed

    }//GEN-LAST:event_btnCuentasActionPerformed

    private void btnTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratamientosActionPerformed

    }//GEN-LAST:event_btnTratamientosActionPerformed

    private void btnOdontogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdontogramaActionPerformed

    }//GEN-LAST:event_btnOdontogramaActionPerformed

    private void btnHistoriaConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaConsultasActionPerformed


    }//GEN-LAST:event_btnHistoriaConsultasActionPerformed

    private void btnProximaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximaConsultaActionPerformed


    }//GEN-LAST:event_btnProximaConsultaActionPerformed

    private void btnTrabajosLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajosLaboratorioActionPerformed

    }//GEN-LAST:event_btnTrabajosLaboratorioActionPerformed

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed


    }//GEN-LAST:event_btnModificarDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcciones;
    public javax.swing.JMenuItem btnAnamnesis;
    public javax.swing.JMenuItem btnCuentas;
    public javax.swing.JMenuItem btnEnviarSMS;
    public javax.swing.JMenuItem btnHistoriaConsultas;
    public javax.swing.JMenuItem btnImagenes;
    public botones.BotonEdicion btnModificar;
    public javax.swing.JMenuItem btnModificarDatos;
    public botones.BotonNuevo btnNuevo;
    public javax.swing.JMenuItem btnOdontograma;
    public javax.swing.JMenuItem btnProximaConsulta;
    public javax.swing.JMenuItem btnTrabajosLaboratorio;
    public javax.swing.JMenuItem btnTratamientos;
    public botones.BotonVolver btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JPopupMenu.Separator jSeparator12;
    public javax.swing.JPopupMenu.Separator jSeparator13;
    public javax.swing.JPopupMenu.Separator jSeparator14;
    public javax.swing.JPopupMenu.Separator jSeparator15;
    public javax.swing.JPopupMenu.Separator jSeparator16;
    public javax.swing.JPopupMenu.Separator jSeparator17;
    public javax.swing.JPopupMenu.Separator jSeparator18;
    public javax.swing.JPopupMenu.Separator jSeparator19;
    public javax.swing.JPopupMenu menuEntradas;
    public javax.swing.JTable tbl;
    public javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
